apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    app.kubernetes.io/name: api-svc
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/name: api-svc
    app.kubernetes.io/component: backend
